/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as JogarRouteImport } from './routes/jogar'
import { Route as ApiPublicWebhooksOnixpayRouteImport } from './routes/api/public/webhooks/onixpay'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const JogarRoute = JogarRouteImport.update({
  id: '/jogar',
  path: '/jogar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksOnixpayRoute =
  ApiPublicWebhooksOnixpayRouteImport.update({
    id: '/api/public/webhooks/onixpay',
    path: '/api/public/webhooks/onixpay',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/jogar': typeof JogarRoute
  '/api/public/webhooks/onixpay': typeof ApiPublicWebhooksOnixpayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/jogar': typeof JogarRoute
  '/api/public/webhooks/onixpay': typeof ApiPublicWebhooksOnixpayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/jogar': typeof JogarRoute
  '/api/public/webhooks/onixpay': typeof ApiPublicWebhooksOnixpayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/auth' | '/dashboard' | '/jogar' | '/api/public/webhooks/onixpay'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/dashboard' | '/jogar' | '/api/public/webhooks/onixpay'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/jogar'
    | '/api/public/webhooks/onixpay'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  JogarRoute: typeof JogarRoute
  ApiPublicWebhooksOnixpayRoute: typeof ApiPublicWebhooksOnixpayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jogar': {
      id: '/jogar'
      path: '/jogar'
      fullPath: '/jogar'
      preLoaderRoute: typeof JogarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/onixpay': {
      id: '/api/public/webhooks/onixpay'
      path: '/api/public/webhooks/onixpay'
      fullPath: '/api/public/webhooks/onixpay'
      preLoaderRoute: typeof ApiPublicWebhooksOnixpayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  JogarRoute: JogarRoute,
  ApiPublicWebhooksOnixpayRoute: ApiPublicWebhooksOnixpayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
